export const ACCESS_TOKEN = 'access_token';
export const REFRESH_TOKEN = 'refresh_token';
export const USER_ID = 'user_id';
export const TIMEOUT_DURATION = 5000;
export const SHOWONBOARDSCREENS = "show_onboard_screens";
export const JWTAUTHENTICATION = 'JWTAUTHENTICATION';
export const LANGUAGECODE = 'languageCode';
export const LANGUAGENAME = 'languageName';
export const MOBILENUMBER = 'mobileNumber';
export const USERNAME = 'userName';
export const LANGUAGEID = 'languageId';
export const ROLDID = 'roleId';
export const ROLENAME = 'roleName';
export const REFERRALCODE = 'referralCode';
export const USER_IMG = "userImg"
export const STATE_ID = "STATEID"
export const DISTRICT_ID = "DISTRICTID"
export const STATE_NAME = "STATE"
export const DISTRICT_NAME = "DISTRICT"
export const FIRSTNAME = 'FIRSTNAME';
export const LASTNAME = 'LASTNAME';
export const OFFLINETOTALCOUNT = "OFFLINETOTALCOUNT";
export const COMPANYCODE="COMPANYCODE";
export const SCREENNAME = 'SCREENNAME';
export const EMP_DASHBOARD_SCREEN = "HomeScreenEmp"
export const DASHBOARD_SCREEN = "HomeScreenRn"
export const APPLICATION_NAME = "subeej";
export const EMP_HIERARCHY="empHierarchy";
export const SDK_AUTH_TOKEN = "SDK_AUTH_TOKEN";
export const SDK_AUTH_ID = "SDK_AUTH_ID";
export const subeejSDK="subeejSDK"