const Others = {
  displayName: 'Others',
  layout: 'Others',
  layoutIcon: require('../../assets/Images/staticProdcutInfoIcon.png'),
  servicesList: [
    {
      fontColor: 'rgba(200, 10, 80, 1)',
      id: 8,
      serviceImage: require('../../assets/Images/staticDipStictIcon.png'),
      status: true,
      subTitle: 'Dipstick',
      title: 'Surveys',
      translatedElement: 'Dipstick',
      translatedTitle: 'Surveys',
      visible: true,
    },
    {
      fontColor: 'rgba(26, 91, 150, 1)',
      id: 9,
      serviceImage: require('../../assets/Images/staticBookIcon.png'),
      status: true,
      subTitle: 'Book',
      title: 'Seeds',
      translatedElement: 'Book',
      translatedTitle: 'SeedsStatic',
      visible: true,
    },
    {
      fontColor: 'rgba(14, 162, 102, 1)',
      id: 10,
      serviceImage: require('../../assets/Images/staticMeetIcon.png'),
      status: true,
      subTitle: 'Meet',
      title: 'Saathi Kisan',
      translatedElement: 'MeetStatic',
      translatedTitle: 'Saathi_Kisan',
      visible: true,
    },
    {
      fontColor: 'rgba(76, 78, 225, 1)',
      id: 12,
      serviceImage: require('../../assets/Images/staticInviteImg.png'),
      status: true,
      subTitle: 'Invite',
      title: 'Farmer Meeting',
      translatedElement: 'InviteStatic',
      translatedTitle: 'Farmer_Meeting',
      visible: true,
    },
    {
      fontColor: '#365E7D',
      id: 13,
      serviceImage: require('../../assets/Images/pestForeCast.png'),
      status: true,
      subTitle: 'Forecast',
      title: 'Pest Forecast',
      translatedElement: 'PEST',
      translatedTitle: 'FORECAST',
      visible: false,
    },
    {
      fontColor: '#70DA40',
      id: 14,
      serviceImage: require('../../assets/Images/advanceKnowledgeIcon.png'),
      status: true,
      subTitle: 'Knowledge Center',
      title: 'Knowledge Center',
      translatedElement: 'KNOWLEDGE',
      translatedTitle: 'CENTER',
      visible: false,
    },
    {
      fontColor: '#0ED2B3',
      id: 14,
      serviceImage: require('../../assets/Images/field_activity_qr.png'),
      status: true,
      subTitle: 'Field Activity QR',
      title: 'Field Activity QR',
      translatedElement: 'FIELD',
      translatedTitle: 'Activity_QR',
      visible: false,
    },
    {
      fontColor: '#70DA40',
      id: 15,
      serviceImage: require('../../assets/Images/scanEarnGif.gif'),
      status: true,
      subTitle: 'Scan & Earn',
      title: 'Scan & Earn',
      translatedElement: 'SCAN',
      translatedTitle: 'EARNCASH',
      visible: true,
    },
    {
      fontColor: '#58BADD',
      id: 16,
      serviceImage: require('../../assets/Images/redeemCashIcon.png'),
      status: true,
      subTitle: 'RedeemCash',
      title: 'RedeemCash',
      translatedElement: 'REDEEM',
      translatedTitle: 'CASH',
      visible: true,
    },
  ],
  showViewAll: true,
};

export default Others;